name: Carbon CI
description: Monitor GitHub Actions job carbon emissions automatically
author: Carbon-CI

branding:
  icon: activity
  color: green

inputs:
  api-key:
    description: Carbon CI API key (store it as a secret)
    required: true

runs:
  using: node20
  pre: pre.js
  pre-if: always()
  main: main.js
  post: post.js
  post-if: always()
